platform :ios, '7.0'
pod 'AFNetworking'
pod 'ZAActivityBar', :git => 'https://github.com/zacaltman/ZAActivityBar.git'
pod 'MBProgressHUD', '~> 0.5'
pod 'SDWebImage', '~>3.6'
pod 'MFSideMenu'
pod 'IQKeyboardManager'
pod 'IQDropDownTextField', :git => 'https://github.com/abmti/IQDropDownTextField.git'
pod 'Reachability', '~> 3.1'
